[workspace]
members = [
    "common-lib",
    "bootloader",
    "bootloader-lib",
    "kernel",
    "kernel-lib",
    "pci",
    "macros"
]



[workspace.dependencies]
x86_64 = "0.14.10"
lazy_static = "1.4.0"
bitfield-struct = "0.3.2"
xhci = "0.9.1"
modular-bitfield = "0.11.2"
num-traits = "0.2.15"