[package]
name = "pci"
version = "0.1.0"
edition = "2021"


[dependencies]

bitfield-struct = "0.3.2"
enum-try-from = "0.0.1"
kernel-lib = { path = "../kernel-lib" }
macros = { path = "../macros", features = ["extra-traits"] }
