[package]
name = "kernel-lib"
version = "0.1.0"
edition = "2021"


[dependencies]
common-lib = { path = "../common-lib" }
once = "0.3.4"
spin = "0.9.5"
uefi = { version = "0.19.0" }


[build-dependencies]
cc = { version = "1.0" }
