[package]
name = "kernel-lib"
version = "0.1.0"
edition = "2021"


[dependencies]
common-lib = { path = "../common-lib" }
once_cell = {version = "1.17.1"}


[build-dependencies]
cc = { version = "1.0" }
