[package]
name = "kernel"
version = "0.1.0"
edition = "2021"



[dependencies]
common-lib = { path = "../common-lib" }
kernel-lib = { path = "../kernel-lib" }
pci = { path = "../pci" }
x86_64 = "0.14.10"
macros = { path = "../macros", features = ["extra-traits"] }
