[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-lib = { path = "../common-lib" }
kernel-lib = { path = "../kernel-lib" }


[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }