[package]
name = "common-lib"
version = "0.1.0"
edition = "2021"


[dependencies]
auto-delegate = { workspace = true }
thiserror-no-std = { version = "2.0.2" }

[features]
default = ["alloc"]

alloc = []